import { emptyView, type TableDocument } from './model/document.ts'

const options = {
  status: [
    { id: 'status-plan', label: '待开始', color: '#eef1f4', textColor: '#52606d' },
    { id: 'status-active', label: '进行中', color: '#e8f0fe', textColor: '#2457a7' },
    { id: 'status-review', label: '待验收', color: '#fef3d0', textColor: '#8b6508' },
    { id: 'status-done', label: '已完成', color: '#e8f8f0', textColor: '#13744b' },
  ],
  tags: [
    { id: 'tag-design', label: '设计', color: '#f3e8ff', textColor: '#7542a2' },
    { id: 'tag-dev', label: '开发', color: '#e8f0fe', textColor: '#2457a7' },
    { id: 'tag-test', label: '测试', color: '#fef3d0', textColor: '#8b6508' },
    { id: 'tag-docs', label: '文档', color: '#e8f8f0', textColor: '#13744b' },
  ],
}

export const demoData: TableDocument = {
  fields: [
    { id: 'project', label: '项目任务', type: 'text' },
    { id: 'status', label: '状态', type: 'select', options: options.status, width: 130 },
    { id: 'progress', label: '进度', type: 'progress', width: 170 },
    { id: 'rating', label: '评分', type: 'rating', width: 175 },
    { id: 'tags', label: '标签', type: 'multi_select', options: options.tags, width: 200 },
    { id: 'due', label: '截止日期', type: 'date', width: 145 },
    { id: 'hours', label: '工时', type: 'number' },
    { id: 'budget', label: '预算（万）', type: 'float', width: 130 },
    { id: 'accepted', label: '已验收', type: 'checkbox', width: 110 },
    { id: 'email', label: '负责人邮箱', type: 'email', width: 220 },
    { id: 'link', label: '项目链接', type: 'link', width: 190 },
    { id: 'created', label: '新建时间', type: 'created_time', width: 190 },
    { id: 'modified', label: '修改时间', type: 'modified_time', width: 190 },
  ],
  rows: [
    {
      id: 'demo-1',
      project: '官网改版',
      status: '进行中',
      progress: '72',
      rating: '4',
      tags: '["设计","开发"]',
      due: new Date('2026-10-18T00:00:00'),
      hours: 48,
      budget: 12.5,
      accepted: false,
      email: 'design@example.com',
      link: '{"text":"设计稿","link":"https://example.com/design"}',
      created: '2026-09-18T03:20:00.000Z',
      modified: '2026-10-04T08:15:00.000Z',
    },
    {
      id: 'demo-2',
      project: '移动端适配',
      status: '待验收',
      progress: '95',
      rating: '5',
      tags: '["开发","测试"]',
      due: new Date('2026-10-12T00:00:00'),
      hours: 64,
      budget: 8.75,
      accepted: false,
      email: 'mobile@example.com',
      link: '{"text":"预览页面","link":"https://example.com/mobile"}',
      created: '2026-09-20T05:40:00.000Z',
      modified: '2026-10-03T10:30:00.000Z',
    },
    {
      id: 'demo-3',
      project: '组件库整理',
      status: '已完成',
      progress: '100',
      rating: '5',
      tags: '["设计","开发","文档"]',
      due: new Date('2026-10-08T00:00:00'),
      hours: 36,
      budget: 5.2,
      accepted: true,
      email: 'ui@example.com',
      link: '{"text":"组件文档","link":"https://example.com/components"}',
      created: '2026-09-12T07:10:00.000Z',
      modified: '2026-10-02T02:45:00.000Z',
    },
    {
      id: 'demo-4',
      project: '性能优化',
      status: '进行中',
      progress: '45',
      rating: '3',
      tags: '["开发","测试"]',
      due: new Date('2026-10-24T00:00:00'),
      hours: 28,
      budget: 4.6,
      accepted: false,
      email: 'perf@example.com',
      link: '{"text":"指标面板","link":"https://example.com/performance"}',
      created: '2026-09-27T01:25:00.000Z',
      modified: '2026-10-05T00:10:00.000Z',
    },
    {
      id: 'demo-5',
      project: '使用指南',
      status: '待开始',
      progress: '10',
      rating: '2',
      tags: '["文档"]',
      due: new Date('2026-10-30T00:00:00'),
      hours: 12,
      budget: 1.35,
      accepted: false,
      email: 'docs@example.com',
      link: '{"text":"文档首页","link":"https://example.com/docs"}',
      created: '2026-10-01T06:00:00.000Z',
      modified: '2026-10-01T06:00:00.000Z',
    },
  ],
  view: { ...emptyView(), name: '项目交付示例', rowHeight: 'medium' },
}
